# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# This file is optimized for use with Angular 2+ with testing support using Gherkin
# and end to end testing performed via BrowserStack.
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # Karma requires the local image to have a browser.
      - image: circleci/node:7.10-browsers
    steps:
      - checkout

      - run:
          name: Setup Angular Command Line
          command: sudo yarn global add @angular/cli
      - run:
          name: Set Angular CLI to use yarn for package management
          command: sudo ng set --global packageManager=yarn
      - run:
          name: Suppress unwanted version mismatch error message
          command: ng set --global warnings.versionMismatch=false
      - run:
          name: Set Protractor to run globally
          command: sudo yarn global add protractor
      - run:  yarn install
      - run:
          name: Start the node webserver and place it in the background as a service.
          command: ng serve
          background: true

      #Begin Tests
      - run:
          name: JS Lint code inspection
          command: ng lint
      - run:
          name: Karma Unit Tests
          command: ng test --watch=false
      - run:
          name: Protractor End to End tests using Cucumber & Gherkin
          command: protractor
